### ISSUE TITLE
ViewModel; Событие навигации

### ISSUE THREAD

**Issue by n-shvedov27** [Team-Finder-dev/TeamFinder_android#10]
Конечная цель задачи в том, чтобы из вьюмеодели можно было инициировать переход на другой экран

- Добавить базовый класс BaseViewModel
- Добавить поле вьюмодели в BaseFragment
- Создать интерфейс NavEvent, с методом navigate(framgnet: Framgent)
- - Создать stateFlow<NavEvent> внутри BaseViewModel
- - Подписаться на этот stateFlow внутри BaseFragment
- - Внутри подписки вызывать метод navigate()
- - Добавить реализации NavEvent, и переписать навигацию на них

**Comment by GoetzDeBouville** [comment]
Поле viewModel уже есть в BaseFragment

**Comment by n-shvedov27** [comment]
Значит осталось только NavEvent добавить

**Comment by GoetzDeBouville** [comment]
По поводу реализации NavEvent, требуется в базовой viewmodel прописать логику навигации? Просто я вижу что мы заюзаем NavController, не совсем понимаю как это должно работать на viewModel, разве что через fragmentManager

**Comment by n-shvedov27** [comment]
Если коротко, то надо добавить возможность emit'ить события навигации из вьюМодели
Логика эта в BaseViewModel должна быть, да
